# Backup location to teleport prisoner on unjail if location before jailed is found corrupt.
backupLocation:
  world: world
  x: 0.0
  y: 0.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

# Counts offline time as sentence time.
offlineTime: false

# Change prisoner group when jailed.
# Needs Vault to be installed.
changeGroup: false
# Group name for prisoner to be moved to when jailed.
prisonerGroup: prisoner

# Automatically save prisoners and jails data files.
# Set to 0 to disable.
autoSaveTimeInMinutes: 5

# Messages shown.
messages:
  # Placeholders for /jail:
  # · {prisoner}: player to be jailed.
  # · {player}: player that executes the command.
  # · {jail}: jail name to where the prisoner will be sent.
  # · {time}: time argument provided.
  # · {reason}: reason argument provided.
  jailSuccess: "&c{prisoner} &6has been jailed by &c{player} &6for &c{time}&6. Reason: {reason}"
  jailInfoPrisoner: "&6You got jailed by {player} for {time} because of {reason}"
  jailFailedPlayerNeverJoined: "&cPlayer &4{prisoner} &cnever joined this server."
  jailFailedPlayerExempt: "&4{prisoner} &ccannot be jailed."
  jailFailedJailNotFound: "&cJail &4{jail} &cnot found."
  jailFailedTimeIncorrect: "&cThe time provided is not valid."
  jailCmdUsage: "&cUsage: /jail <player> <jail> <time> <reason>"
  # Placeholders for /jail info:
  # · {prisoner}: player to retrieve the status and info.
  # · {player}: player that executes the command.
  infoFailedPlayerNotJailed: "&6The player you are requesting the information from is not currently serving a sentence."
  infoFailedPlayerNeverJoined: "&6Player &c{prisoner} &6never joined this server."
  infoCmdUsage: "&cUsage: /jail info <player>"
  ownInfoFailedPlayerNotJailed: "&6You are not in jail."
  ownInfoCmdUsage: "§cUsage: /jail info"

  # Placeholders for /unjail:
  # · {prisoner}: player to be unjailed.
  # · {player}: player that executes the command.
  unjailSuccess: "&c{prisoner} &6has been unjailed by &c{player}&6."
  unjailInfoPrisoner: "You got unjailed by {player}"
  unjailFailedPlayerNotJailed: "&c{prisoner} &6could not be unjailed, player wasn't jailed."
  unjailFailedPlayerNeverJoined: "&6Player &c{prisoner} &6never joined this server."

  # Placeholders for /setjail and /deljail:
  # · {player}: player that executes the command.
  # · {jail}: jail name to be added/removed.
  setjailFromConsole: "&cOnly players can set jails!"
  setjailSuccess: "&6Jail added successfully!"
  deljailSuccess: "&6Jail removed successfully!"
  deljailFailed: "&cThat jail does not exist!"

  # Placeholders for /betterjails reload and /betterjails save:
  # · {player}: player that executes the command.
  reload: "&6Files reloaded successfully!"
  save: "&6Files saved successfully!"

  jailInfoText: "&7Info for jailed player:\n\n
      &7· Name: &f{prisoner}\n
      &7· UUID: &f{uuid}\n
      &7· Time left: &f{time}{timeUnit}\n
      &7· Jailed in jail: &f{jail}\n
      &7· Jailed by: &f{player}\n
      &7· Location before jailed: &f{lastLocation}\n
      &7· Primary group: &f{primaryGroup}\n
      &7· Reason: &f{reason}\n
      &7· All parent groups: &f{parentGroups}
    "

  jailOwnInfoText: "&7Jail Info:\n\n
      &7· Time left: &f{time}{timeUnit}\n
      &7· Jailed by: &f{player}\n
      &7· Reason: &f{reason}\n
    "

  # Placeholders for /jails premessages:
  # · None :(
  listNoJails: "&6There are no jails available!"
  listJailsPremessage: "&6Available jails:"

  # Placeholders for /jails list:
  # · None :(
  jailsFormat: "line"

  # jailsFormat can be any of these values:
  # · list
  # · line
  #
  # Examples:
  #   list:
  #     · jail1
  #     · jail2
  #     · jail3
  #   line:
  #     jail1, jail2, jail3.
